org: poojitha61
app: hms-email-service
service: hms-email-service

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

functions:
  sendEmail:
    handler: handler.send_email
    timeout: 30
    events:
      - http:
          path: send-email
          method: post
          cors: true